### ISSUE TITLE
Node bridge

### ISSUE THREAD

**Issue by hugentoblerd** [joni2back/angular-filemanager#106]
I'm very interested in a node bridge and was wondering if that was currently being worked on. I would be interested in contributing.

**Comment by joni2back** [comment]
Hi @hugentoblerd , Node bridge is not developed yet.
I'm very interested to have this for the project (i was thinking in expressJS)
So, if you are interested, you can propose a pull request to add to the project.
For backend side, Me in particular, Im very busy right now with the project frontend side in order to support/handle multiple files and drag and drop features.

Regards!

**Comment by fkoester** [comment]
Hi @hugentoblerd, in my project I include a Node.js bridge (using Express). I intent to publish it as an own project in the next days.

**Comment by hugentoblerd** [comment]
Hey @fkoester, that's awesome! Will you let me know when you publish it?

**Comment by fkoester** [comment]
@hugentoblerd of course!

**Comment by fkoester** [comment]
@hugentoblerd @joni2back Checkout my initial prototype for a Node.js bridge here:

https://github.com/fkoester/angular-filemanager-nodejs-bridge
