### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by gmohite7** [joni2back/angular-filemanager#129]
Hi joni.I am very new to angularJs and would like to install and run your application.I installed the angular-filemanager per instructions in the readme however when i open up index.html i only see a blan application.Can you please advise me how do i run this app to get one similar to one shown in the demo ? Thanks for your help in advance

**Comment by DarkStar1** [comment]
@gmohite7 Just drop create an apache vhost and symlink the root folder of the project.
I however found that the php bridge doesn't work for me at all. Too many issues to jump over.
So I would recommend using [Fabian Köster's nodeJS bride](https://github.com/fkoester/angular-filemanager-nodejs-bridge)

**Comment by durasj** [comment]
You could also try my php local bridge ... In most cases it is easier to get up and running. Just edit the config.js in /src/js/providers directory ...

`            listUrl: 'bridges/php-local',
            uploadUrl: 'bridges/php-local',
            renameUrl: 'bridges/php-local',
            copyUrl: 'bridges/php-local',
            moveUrl: 'bridges/php-local',
            removeUrl: 'bridges/php-local',
            editUrl: 'bridges/php-local',
            getContentUrl: 'bridges/php-local',
            createFolderUrl: 'bridges/php-local',
            downloadFileUrl: 'bridges/php-local',
            downloadMultipleUrl: 'bridges/php-local',
            compressUrl: 'bridges/php-local',
            extractUrl: 'bridges/php-local',
            permissionsUrl: 'bridges/php-local',`

But more modern PHP is needed.

**Comment by DarkStar1** [comment]
@durasj Would 5.6 be sufficient or should I just go for 7?

**Comment by DarkStar1** [comment]
@durasj On php v5.6.20 when I change the parameter of the file manager api to include a path (absolute from root file system) **$fileManagerApi = new FileManagerApi('/Users/darkstar1/Desktop/test', 'en');**
It doesn't work and I get the following error in the apache log:

> PHP Notice:  Undefined index: action in /Users/darkstar1/Projects/e-ark/viewers/modules/eArk-filemanager/bridges/php-local/LocalBridge/FileManagerApi.php on line 173, referer: http://localhost/

**Comment by durasj** [comment]
Strange ... filemanger should send POST request instead of GET for file list ... Or are you trying to do something else? Like multiple file download?

**Comment by DarkStar1** [comment]
No. Nothing at all. This is when I am trying to load the app. I am not php saavy at all so I can't debug this issue.

**Comment by durasj** [comment]
Well I think the change in path is probably not the problem here. I was testing it with PHP 5.6 and PHP 7.0 and it worked out of the box and I can't reproduce your problem.

It looks like there is some GET request. Can you check developer console in browser and tell if there is anything in console and what requests are sent to bridge?

**Comment by DarkStar1** [comment]
Ok the issues I faced are due to the php version I am using (according to my friend that helped me debug the php). 
First there needed to be a "/" at the end of the actions url so 
listUrl: 'bridges/php-local', becomes listUrl: 'bridges/php-local/',

Second I created a .htaccess file in the php-local root to add the following settings:
php_value date.timezone "Europe/Copenhagen"
php_value always_populate_raw_post_data -1

**Comment by durasj** [comment]
Glad it works!

The problem wasn't in the PHP version but probably configuration of your webserver (nginx, apache, built-in) and PHP. In the most cases trailing slash is not required. Changes in php.ini are right on the spot :)
