### ISSUE TITLE
Error 500 for extracting and compressing files and upload failed for some files

### ISSUE THREAD

**Issue by haxxorsid** [joni2back/angular-filemanager#259]
I am experiencing error 500 for extracting and compressing files.
I have tried using this [Repo](https://github.com/durasj/angular-filemanager) by @durasj. But still problem not solved. And I am also recieving upload failed error for some files, I don't why, is there any limited size set for uploading a file? Because there is no problem with my php.ini settings.

**Comment by durasj** [comment]
Hi @haxxorsid, I am afraid I need more debugging info like PHP error logs or some client side JS error I can start from. Extracting should be fine. Compression / downloading multiple files is currently not supported, see #225, due to some problems. There will be some update soon.

Regarding the file size, looking at the [config](https://github.com/joni2back/angular-filemanager/blob/master/src/js/providers/config.js) I can't see any setting like that and I don't remember I would implement any restrictions on the upload component. Maybe you could check your web server configuration which is in front of the PHP. Like Apache or Nginx.

**Comment by durasj** [comment]
Hi @haxxorsid,

extracting/compression and multiple files download was fixed in the local php bridge and will be probably merged to the main repo in the future. [Latest bundle](https://github.com/durasj/angular-filemanager/tree/bundle-php-local) already contains all fixes.
