### ISSUE TITLE
How to repackage after making changes?

### ISSUE THREAD

**Issue by enayetn** [joni2back/angular-filemanager#318]
I'd like to make some updates to suit my needs, but I am not sure how to repackage the app as a single minified JS file, as you have it in the dist folder. Could you point me in the right direction? 

Thanks!

**Comment by joni2back** [comment]
Hey @enayetn as @durasj told you, you change the files then do the build (in order to minify the files)

You first need to do a `yarn install` (or npm install in order to get all dev dependencies)

then execute the build using the following command: 
`gulp build || node node_modules/gulp/bin/gulp.js build`

**Comment by enayetn** [comment]
Perfect, thanks!
