### ISSUE TITLE
Extraction started in a background process

### ISSUE THREAD

**Issue by Vikas-Stormy** [joni2back/angular-filemanager#37]
hello jonas ,
i been using angular-filemanager the issue is when ever i made a request to compress or Extract 

the pop up is staying still even after the completion of the extract  on compress , explictly making user to close that popup and it is not giving the completion dialouge 

Thank  jonas You nice work

**Comment by joni2back** [comment]
Hi @Vikas-Stormy , Yes... this behavior is because the compression or extraction process could take long time.. then we show a message (like.. the extraction will start in a background process).
But its great to know there are people that is using this in another way (synchronous), so I will add a parameter in config.js to choose the way that compress&extract works

**Comment by Vikas-Stormy** [comment]
hm okay thank you jonas do inform me that .

**Comment by Vikas-Stormy** [comment]
jonas i think adding  a button or  something stating that  do continue with your work  by  clicking on something or the other way which backs them to the page , ofcourse we can do that by clicking outside part of the popup , but by the perception  people will wait for some instruction to procced further . so plz think up on this as this is highly useful when we are dealing with heavy files

**Comment by joni2back** [comment]
Done!
