### ISSUE TITLE
How can I change directory, where files and folders located ?

### ISSUE THREAD

**Issue by spaun299** [joni2back/angular-filemanager#52]

**Comment by joni2back** [comment]
Hi @spaun299, can you explain with more details? Thanks

**Comment by spaun299** [comment]
I'm writing connector for Python. And when I open your filemanager in my
project , list of files is empty... How can I tell to filemanager show
files from some folder. JSON give this request : Object { mode="list",
onlyFolders=false, path="/"}
But I need to change path for my own
It's probably stupid question but I can't solve this problem.
Sorry , and thanks

2015-07-21 14:17 GMT+03:00 Jonas Sciangula Street <notifications@github.com>
:

**Comment by joni2back** [comment]
The folder to list files is the path that are you receiving by the request content ```path="/"```
So, for example you need to do something like connect by ftp to the defined path folder...
If you want, you can do a pull request of your python connector in order to collaborate with the project and solve any kind of issues!
Regards.
