### ISSUE TITLE
Request for documentation

### ISSUE THREAD

**Issue by pallavsipani** [joni2back/angular-filemanager#53]
I am struggling to understand some of the logic and without documentation, I have hit a roadblock.
Whenever you have time, can you please add appropriate comments for functions like:
FileNavigator.prototype.buildTree(in filenavigator.js) - Exactly how it works?
$scope.touch (in controller.js)- Again what exactly what does it do?
Generally, a line or 2 for every non-trivial finction will be appreciated. Thanks.

**Comment by joni2back** [comment]
I'm not used to leave comments in the code, but I can explain here..

**FileNavigator.prototype.buildTree** Performs a recursive function in the folder list request, in order to generate the left sidebar navigation tree, it stores an history of directories, for example

```javascript
{
    "name": "public_html",
    childs: [{
        name: "images",
        childs: []
    }, {
        name: "documents",
        childs: [{
            name: "excel",
            childs: []
        }]
    }]
}
```

**$scope.touch** Is the function that is called when you click a file/folder in the frontend, 
this instance is asigned to the $temp variable in order to generate changes or perform actions... for example an edition...
FYI: this file object is reseted with all default values (as was served from the API) when the function is executed.
